import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface HookConfig {
  eventType: string;
  command: string;
  hookId: string;
  matcher?: string;
  timeout?: number;
}

export function generateSessionStartHook(): string {
  return `#!/usr/bin/env node
// kai-session-start — inject profile context into new Claude Code sessions
// Generated by Kai skills install. Do not edit manually.
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");

function getProfileSummary() {
  const dbPath = process.env.KAI_DB || path.join(os.homedir(), ".kai", "kai.db");
  if (!fs.existsSync(dbPath)) return null;

  try {
    const { Database } = require("bun:sqlite");
    const db = new Database(dbPath, { readonly: true });
    const traits = db.query("SELECT dimension, value, confidence FROM traits ORDER BY dimension").all();
    const identityRow = db.query("SELECT name, role FROM identity LIMIT 1").get();
    db.close();

    if (!traits || traits.length === 0) return null;
    return { identity: identityRow, traits: traits };
  } catch {
    return null;
  }
}

try {
  const profile = getProfileSummary();
  if (profile && profile.traits.length > 0) {
    const topTraits = profile.traits
      .filter(t => t.value > 0.5)
      .slice(0, 5)
      .map(t => t.dimension + "=" + t.value.toFixed(2))
      .join(", ");
    const name = profile.identity?.name ? " (" + profile.identity.name + ")" : "";
    console.log("Kai profile active" + name + ". Top traits: " + topTraits);
  }
} catch {
  // Hooks must not block session startup
}
`;
}

export function generateAutoObserveHook(): string {
  return `#!/usr/bin/env node
// kai-auto-observe — detect tool usage patterns and submit observations
// Generated by Kai skills install. Do not edit manually.
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");

const STATE_FILE = path.join(os.homedir(), ".kai", "auto-observe-state.json");
const PATTERN_THRESHOLD = 5;

function loadState() {
  try {
    if (fs.existsSync(STATE_FILE)) {
      return JSON.parse(fs.readFileSync(STATE_FILE, "utf-8"));
    }
  } catch {
    // Reset on corruption
  }
  return { toolCounts: {}, lastReset: new Date().toISOString() };
}

function saveState(state) {
  try {
    const dir = path.dirname(STATE_FILE);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(STATE_FILE, JSON.stringify(state));
  } catch {
    // Best effort
  }
}

function detectPattern(state) {
  const patterns = [];
  for (const [tool, count] of Object.entries(state.toolCounts)) {
    if (count >= PATTERN_THRESHOLD) {
      patterns.push(tool + ":" + count);
    }
  }
  return patterns.length > 0 ? patterns.join(", ") : null;
}

try {
  let input = "";
  try {
    input = fs.readFileSync(0, "utf-8");
  } catch {
    // No stdin data
  }

  const parsed = input ? JSON.parse(input) : {};
  const toolName = parsed.tool_name || parsed.tool || "";

  if (!toolName) return;

  const state = loadState();
  state.toolCounts[toolName] = (state.toolCounts[toolName] || 0) + 1;
  saveState(state);

  const pattern = detectPattern(state);
  if (pattern) {
    console.log("kai-auto-observe: pattern detected — " + pattern);
    state.toolCounts = {};
    saveState(state);
  }
} catch {
  // Hooks must not block tool execution
}
`;
}

interface HookGroup {
  matcher?: string;
  hooks: Array<{
    type: string;
    command: string;
    timeout?: number;
    statusMessage?: string;
  }>;
}

interface SettingsJson {
  hooks?: Record<string, HookGroup[]>;
  [key: string]: unknown;
}

function isKaiHook(command: string, hookId: string): boolean {
  return (
    command.includes(hookId) ||
    command.includes("kai-session-start") ||
    command.includes("kai-auto-observe")
  );
}

export function mergeHookIntoSettings(
  settings: SettingsJson,
  config: HookConfig,
): SettingsJson {
  const result = structuredClone(settings);
  if (!result.hooks) result.hooks = {};
  if (!result.hooks[config.eventType]) result.hooks[config.eventType] = [];

  const groups = result.hooks[config.eventType];

  for (const group of groups) {
    for (let i = 0; i < group.hooks.length; i++) {
      if (isKaiHook(group.hooks[i].command, config.hookId)) {
        group.hooks[i] = {
          type: "command",
          command: config.command,
          ...(config.timeout ? { timeout: config.timeout } : {}),
        };
        return result;
      }
    }
  }

  const newGroup: HookGroup = {
    ...(config.matcher ? { matcher: config.matcher } : {}),
    hooks: [
      {
        type: "command",
        command: config.command,
        ...(config.timeout ? { timeout: config.timeout } : {}),
      },
    ],
  };
  groups.push(newGroup);

  return result;
}

export function removeHookFromSettings(
  settings: SettingsJson,
  config: { eventType: string; hookId: string },
): SettingsJson {
  const result = structuredClone(settings);
  if (!result.hooks?.[config.eventType]) return result;

  const groups = result.hooks[config.eventType];
  for (const group of groups) {
    group.hooks = group.hooks.filter(
      (h) => !isKaiHook(h.command, config.hookId),
    );
  }
  result.hooks[config.eventType] = groups.filter((g) => g.hooks.length > 0);

  return result;
}

export function writeHookScripts(hooksDir: string): void {
  mkdirSync(hooksDir, { recursive: true });
  writeFileSync(
    join(hooksDir, "kai-session-start.cjs"),
    generateSessionStartHook(),
  );
  writeFileSync(
    join(hooksDir, "kai-auto-observe.cjs"),
    generateAutoObserveHook(),
  );
}

export function getHookConfigs(hooksDir: string): HookConfig[] {
  return [
    {
      eventType: "SessionStart",
      command: `bun "${join(hooksDir, "kai-session-start.cjs")}"`,
      hookId: "kai-session-start",
    },
    {
      eventType: "PostToolUse",
      matcher: "Bash|Read|Edit|Write",
      command: `bun "${join(hooksDir, "kai-auto-observe.cjs")}"`,
      hookId: "kai-auto-observe",
      timeout: 10,
    },
  ];
}
