import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export interface HookConfig {
  eventType: string;
  command: string;
  hookId: string;
  matcher?: string;
  timeout?: number;
}

export const KAI_HOOK_IDS = ["kai-session-start", "kai-auto-observe"] as const;
export const KAI_HOOK_SCRIPTS = [
  "kai-session-start.cjs",
  "kai-auto-observe.cjs",
] as const;

export function generateSessionStartHook(): string {
  return `#!/usr/bin/env node
// kai-session-start — inject profile context into new Claude Code sessions
// Generated by Kai skills install. Do not edit manually.
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");

function getProfileSummary() {
  const dbPath = process.env.KAI_DB || path.join(os.homedir(), ".kai", "kai.db");
  if (!fs.existsSync(dbPath)) return null;

  try {
    const { Database } = require("bun:sqlite");
    const db = new Database(dbPath, { readonly: true });
    const traits = db.query("SELECT dimension, value, confidence FROM traits ORDER BY dimension").all();
    const identityRow = db.query("SELECT name, role FROM identity LIMIT 1").get();
    db.close();

    if (!traits || traits.length === 0) return null;
    return { identity: identityRow, traits: traits };
  } catch {
    return null;
  }
}

try {
  const profile = getProfileSummary();
  if (profile && profile.traits.length > 0) {
    const topTraits = profile.traits
      .filter(t => t.value > 0.5)
      .slice(0, 5)
      .map(t => t.dimension + "=" + t.value.toFixed(2))
      .join(", ");
    const name = profile.identity?.name ? " (" + profile.identity.name.charAt(0).toUpperCase() + ")" : "";
    console.log("Kai profile active" + name + ". Top traits: " + topTraits);
  }
} catch {
  // Hooks must not block session startup
}
`;
}

export function generateAutoObserveHook(): string {
  return `#!/usr/bin/env node
// kai-auto-observe — detect tool usage patterns and submit observations
// Generated by Kai skills install. Do not edit manually.
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");
const crypto = require("crypto");

const STATE_FILE = path.join(os.homedir(), ".kai", "auto-observe-state.json");
const DB_PATH = process.env.KAI_DB || path.join(os.homedir(), ".kai", "kai.db");
const PATTERN_THRESHOLD = 5;

function atomicWriteJson(filePath, data) {
  try {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const tmp = path.join(dir, ".kai-observe-" + crypto.randomUUID() + ".tmp");
    fs.writeFileSync(tmp, JSON.stringify(data));
    fs.renameSync(tmp, filePath);
  } catch {
    // Best effort
  }
}

function loadState() {
  try {
    if (fs.existsSync(STATE_FILE)) {
      return JSON.parse(fs.readFileSync(STATE_FILE, "utf-8"));
    }
  } catch {
    // Reset on corruption
  }
  return { toolCounts: {}, lastReset: new Date().toISOString() };
}

function saveState(state) {
  atomicWriteJson(STATE_FILE, state);
}

function submitObservation(toolName, count) {
  try {
    if (!fs.existsSync(DB_PATH)) return;
    const { Database } = require("bun:sqlite");
    const db = new Database(DB_PATH);
    db.query(
      "INSERT INTO observations (type, key, value, confidence, source, provenance, ts) VALUES ($type, $key, $value, $confidence, $source, $provenance, datetime('now'))"
    ).run({
      $type: "tool_pattern",
      $key: toolName,
      $value: String(count),
      $confidence: "0.6",
      $source: "auto-observe",
      $provenance: "threshold=" + PATTERN_THRESHOLD,
    });
    db.close();
  } catch {
    // Non-critical — observation submission is best effort
  }
}

function detectPattern(state) {
  const patterns = [];
  for (const [tool, count] of Object.entries(state.toolCounts)) {
    if (count >= PATTERN_THRESHOLD) {
      patterns.push({ tool, count });
      submitObservation(tool, count);
    }
  }
  return patterns.length > 0 ? patterns.map(p => p.tool + ":" + p.count).join(", ") : null;
}

try {
  let input = "";
  try {
    input = fs.readFileSync(0, "utf-8");
  } catch {
    // No stdin data
  }

  const parsed = input ? JSON.parse(input) : {};
  const toolName = parsed.tool_name || parsed.tool || "";

  if (!toolName || typeof toolName !== "string") return;
  if (!/^[a-zA-Z0-9_.]+$/.test(toolName)) return;

  const state = loadState();
  state.toolCounts[toolName] = (state.toolCounts[toolName] || 0) + 1;
  saveState(state);

  const pattern = detectPattern(state);
  if (pattern) {
    console.log("kai-auto-observe: pattern detected — " + pattern);
    state.toolCounts = {};
    state.lastReset = new Date().toISOString();
    saveState(state);
  }
} catch {
  // Hooks must not block tool execution
}
`;
}

interface HookGroup {
  matcher?: string;
  hooks: Array<{
    type: string;
    command: string;
    timeout?: number;
    statusMessage?: string;
  }>;
}

interface SettingsJson {
  hooks?: Record<string, HookGroup[]>;
  [key: string]: unknown;
}

function isKaiHook(command: string): boolean {
  return KAI_HOOK_IDS.some((id) => {
    const escaped = id.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    return new RegExp(`(?:^|[/\\\\])${escaped}(?:\\.cjs)?(?:\\s|$|"|')`).test(
      command,
    );
  });
}

export function mergeHookIntoSettings(
  settings: SettingsJson,
  config: HookConfig,
): SettingsJson {
  const result = structuredClone(settings);
  if (!result.hooks) result.hooks = {};
  if (!result.hooks[config.eventType]) result.hooks[config.eventType] = [];

  const groups = result.hooks[config.eventType];

  for (const group of groups) {
    for (let i = 0; i < group.hooks.length; i++) {
      if (isKaiHook(group.hooks[i].command)) {
        group.hooks[i] = {
          type: "command",
          command: config.command,
          ...(config.timeout ? { timeout: config.timeout } : {}),
        };
        return result;
      }
    }
  }

  const newGroup: HookGroup = {
    ...(config.matcher ? { matcher: config.matcher } : {}),
    hooks: [
      {
        type: "command",
        command: config.command,
        ...(config.timeout ? { timeout: config.timeout } : {}),
      },
    ],
  };
  groups.push(newGroup);

  return result;
}

export function removeHookFromSettings(
  settings: SettingsJson,
  config: { eventType: string; hookId: string },
): SettingsJson {
  const result = structuredClone(settings);
  if (!result.hooks?.[config.eventType]) return result;

  const groups = result.hooks[config.eventType];
  for (const group of groups) {
    group.hooks = group.hooks.filter((h) => !isKaiHook(h.command));
  }
  result.hooks[config.eventType] = groups.filter((g) => g.hooks.length > 0);

  return result;
}

export function writeHookScripts(hooksDir: string): void {
  mkdirSync(hooksDir, { recursive: true });
  writeFileSync(
    join(hooksDir, KAI_HOOK_SCRIPTS[0]),
    generateSessionStartHook(),
  );
  writeFileSync(join(hooksDir, KAI_HOOK_SCRIPTS[1]), generateAutoObserveHook());
}

export function getHookConfigs(hooksDir: string): HookConfig[] {
  return [
    {
      eventType: "SessionStart",
      command: `bun "${join(hooksDir, KAI_HOOK_SCRIPTS[0])}"`,
      hookId: KAI_HOOK_IDS[0],
    },
    {
      eventType: "PostToolUse",
      matcher: "Bash|Read|Edit|Write",
      command: `bun "${join(hooksDir, KAI_HOOK_SCRIPTS[1])}"`,
      hookId: KAI_HOOK_IDS[1],
      timeout: 10,
    },
  ];
}
