export function generateAutoObserveHook(): string {
  return `#!/usr/bin/env node
// kai-auto-observe — detect tool usage patterns and submit observations
// Generated by Kai skills install. Do not edit manually.
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");
const crypto = require("crypto");

const STATE_FILE = path.join(os.homedir(), ".kai", "auto-observe-state.json");
const DB_PATH = process.env.KAI_DB || path.join(os.homedir(), ".kai", "kai.db");
const PATTERN_THRESHOLD = 5;

function atomicWriteJson(filePath, data) {
  try {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    const tmp = path.join(dir, ".kai-observe-" + crypto.randomUUID() + ".tmp");
    fs.writeFileSync(tmp, JSON.stringify(data));
    fs.renameSync(tmp, filePath);
  } catch {
    // Best effort
  }
}

function loadState() {
  try {
    if (fs.existsSync(STATE_FILE)) {
      return JSON.parse(fs.readFileSync(STATE_FILE, "utf-8"));
    }
  } catch {
    // Reset on corruption
  }
  return { toolCounts: {}, lastReset: new Date().toISOString() };
}

function saveState(state) {
  atomicWriteJson(STATE_FILE, state);
}

function submitObservation(toolName, count) {
  try {
    if (!fs.existsSync(DB_PATH)) return;
    const { Database } = require("bun:sqlite");
    const db = new Database(DB_PATH);
    db.query(
      "INSERT INTO observations (type, key, value, confidence, source, provenance, ts) VALUES ($type, $key, $value, $confidence, $source, $provenance, datetime('now'))"
    ).run({
      $type: "tool_pattern",
      $key: toolName,
      $value: String(count),
      $confidence: "0.6",
      $source: "auto-observe",
      $provenance: "threshold=" + PATTERN_THRESHOLD,
    });
    db.close();
  } catch {
    // Non-critical — observation submission is best effort
  }
}

function detectPattern(state) {
  const patterns = [];
  for (const [tool, count] of Object.entries(state.toolCounts)) {
    if (count >= PATTERN_THRESHOLD) {
      patterns.push({ tool, count });
      submitObservation(tool, count);
    }
  }
  return patterns.length > 0 ? patterns.map(p => p.tool + ":" + p.count).join(", ") : null;
}

try {
  let input = "";
  try {
    input = fs.readFileSync(0, "utf-8");
  } catch {
    // No stdin data
  }

  const parsed = input ? JSON.parse(input) : {};
  const toolName = parsed.tool_name || parsed.tool || "";

  if (!toolName || typeof toolName !== "string") return;
  if (!/^[a-zA-Z0-9_.]+$/.test(toolName)) return;

  const state = loadState();
  state.toolCounts[toolName] = (state.toolCounts[toolName] || 0) + 1;
  saveState(state);

  const pattern = detectPattern(state);
  if (pattern) {
    console.log("kai-auto-observe: pattern detected — " + pattern);
    state.toolCounts = {};
    state.lastReset = new Date().toISOString();
    saveState(state);
  }
} catch {
  // Hooks must not block tool execution
}
`;
}
