import {
  ALLOWED_TOOLS,
  BUSY_TIMEOUT_MS,
  MIN_SCHEMA_VERSION,
} from "./constants";

export function generateAutoObserveHook(): string {
  return `#!/usr/bin/env bun
// kai-auto-observe — observe tool usage and write structured observations
// Generated by Kai autopilot. Do not edit manually.
// FIXED: type=tool_usage (was invalid), confidence=7 int (was string) [D4]
// PRIVACY: Only captures allowlisted tool categories [D19]
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");

const DB_PATH = process.env.KAI_DB || path.join(os.homedir(), ".kai", "kai.db");
const MIN_SCHEMA_VERSION = ${MIN_SCHEMA_VERSION};
const BUSY_TIMEOUT_MS = ${BUSY_TIMEOUT_MS};

// [D19] Tool category allowlist — only behaviorally meaningful tools
const ALLOWED_TOOLS = new Set(${JSON.stringify([...ALLOWED_TOOLS])});

try {
  let input = "";
  try { input = fs.readFileSync(0, "utf-8"); } catch {}
  const parsed = input ? JSON.parse(input) : {};

  const toolName = parsed.tool_name || parsed.tool || "";
  if (!toolName || typeof toolName !== "string") process.exit(0);
  if (!/^[a-zA-Z0-9_.]+$/.test(toolName)) process.exit(0);

  // [D19] Privacy: skip non-allowlisted tools
  if (!ALLOWED_TOOLS.has(toolName)) process.exit(0);

  const sessionId = parsed.session_id || null;
  const cwd = parsed.cwd || process.cwd();

  if (!fs.existsSync(DB_PATH)) process.exit(0);

  const { Database } = require("bun:sqlite");
  const db = new Database(DB_PATH);

  // [D18] Schema version gate — skip if migration not yet run
  try {
    const row = db.query("SELECT MAX(version) as v FROM schema_version").get();
    if (!row || row.v < MIN_SCHEMA_VERSION) { db.close(); process.exit(0); }
  } catch { db.close(); process.exit(0); }

  db.run("PRAGMA busy_timeout = " + BUSY_TIMEOUT_MS);

  // Build observation value — capture only input keys (not values) for privacy
  const toolInput = parsed.tool_input || {};
  const value = JSON.stringify({
    tool: toolName,
    session_id: sessionId,
    cwd: cwd,
    input_keys: Object.keys(toolInput),
  });

  db.query(
    "INSERT INTO observations (type, key, value, confidence, source, provenance, session_id, ts) VALUES (?, ?, ?, ?, ?, ?, ?, datetime('now'))"
  ).run(
    "tool_usage",
    toolName,
    value,
    7,
    "auto_observe",
    JSON.stringify({ session_id: sessionId, autopilot: true }),
    sessionId,
  );

  db.close();
} catch {
  // Hooks must never block tool execution
}
`;
}
