export function generateSessionStartHook(): string {
  return `#!/usr/bin/env bun
// kai-session-start — inject profile context + nudges into new Claude Code sessions
// Generated by Kai autopilot. Do not edit manually.
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");

const DB_PATH = process.env.KAI_DB || path.join(os.homedir(), ".kai", "kai.db");
const MIN_SCHEMA_VERSION = 9;

// Nudge templates (Phase 1: rule-based from top traits)
const NUDGE_TEMPLATES = [
  { trait: "autonomy", min: 0.7, template: "User prefers direct execution; skip explanations unless blocked." },
  { trait: "detail_oriented", min: 0.7, template: "User values thoroughness; provide comprehensive context." },
  { trait: "detail_oriented", max: 0.3, template: "User prefers concise output; keep responses brief." },
  { trait: "disliked_behavior", min: 0.5, template: "User has strong behavioral dislikes; respect past corrections." },
];

function generateNudges(traits) {
  const sorted = traits
    .filter(t => t.confidence >= 5)
    .sort((a, b) => b.confidence - a.confidence)
    .slice(0, 3);
  const nudges = [];
  for (const trait of sorted) {
    for (const tmpl of NUDGE_TEMPLATES) {
      if (tmpl.trait !== trait.dimension) continue;
      const matches = (tmpl.min !== undefined && trait.value >= tmpl.min) ||
                      (tmpl.max !== undefined && trait.value <= tmpl.max);
      if (matches) {
        nudges.push("[kai] " + tmpl.template + " (" + trait.dimension + "=" + trait.value.toFixed(2) + ")");
      }
    }
  }
  return nudges;
}

try {
  // Parse stdin for session_id
  let input = "";
  try { input = fs.readFileSync(0, "utf-8"); } catch {}
  const parsed = input ? JSON.parse(input) : {};
  const sessionId = parsed.session_id || ("ts-" + Date.now() + "-" + Math.random().toString(36).slice(2, 8));
  const projectPath = parsed.cwd || process.cwd();

  if (!fs.existsSync(DB_PATH)) {
    console.log("[kai] No profile database yet. Observing your work style. Adaptive guidance will appear next session.");
    process.exit(0);
  }

  const { Database } = require("bun:sqlite");
  const db = new Database(DB_PATH);

  // [D18] Schema version gate
  try {
    const row = db.query("SELECT MAX(version) as v FROM schema_version").get();
    if (!row || row.v < MIN_SCHEMA_VERSION) {
      // Old schema — fall back to basic profile read
      try {
        const traits = db.query("SELECT dimension, value, confidence FROM traits ORDER BY dimension").all();
        if (traits && traits.length > 0) {
          const topTraits = traits.filter(t => t.value > 0.5).slice(0, 5)
            .map(t => t.dimension + "=" + t.value.toFixed(2)).join(", ");
          console.log("Kai profile active. Top traits: " + topTraits);
        }
      } catch {}
      db.close();
      process.exit(0);
    }
  } catch { db.close(); process.exit(0); }

  db.run("PRAGMA busy_timeout = 5000");

  // [D20] Orphan session cleanup — close stale pending sessions (> 1 hour old)
  try {
    db.query(
      "UPDATE autopilot_sessions SET stopped_at = datetime('now', '-1 hour'), derivation_status = 'skipped' WHERE stopped_at IS NULL AND started_at < datetime('now', '-1 hour')"
    ).run();
  } catch {}

  // Write session marker
  db.query(
    "INSERT INTO autopilot_sessions (session_id, started_at, derivation_status, project_path) VALUES (?, datetime('now'), 'pending', ?)"
  ).run(sessionId, projectPath);

  // Read profile (LIMIT 10 for performance)
  const traits = db.query("SELECT dimension, value, confidence FROM traits ORDER BY confidence DESC LIMIT 10").all();
  const identityRow = db.query("SELECT name, role FROM identity LIMIT 1").get();

  // Get last session observation count
  let lastCount = 0;
  try {
    const lastSession = db.query("SELECT observations_count FROM autopilot_sessions WHERE stopped_at IS NOT NULL ORDER BY stopped_at DESC LIMIT 1").get();
    lastCount = lastSession ? lastSession.observations_count : 0;
  } catch {}

  db.close();

  if (!traits || traits.length === 0) {
    console.log("[kai] Observing your work style. Adaptive guidance will appear next session.");
  } else {
    const nudges = generateNudges(traits);
    const topTraits = traits
      .filter(t => t.value > 0.5)
      .slice(0, 5)
      .map(t => t.dimension + "=" + t.value.toFixed(2))
      .join(", ");
    const name = identityRow?.name ? " (" + identityRow.name.charAt(0).toUpperCase() + ")" : "";
    const lastInfo = lastCount > 0 ? " | Last session: " + lastCount + " observations" : "";
    console.log("Kai profile active" + name + ". Top traits: " + topTraits + lastInfo);
    for (const nudge of nudges) {
      console.log(nudge);
    }
  }
} catch (err) {
  // Hooks must never block session startup
  try { console.log("[kai] Profile load error — operating in passive mode."); } catch {}
}
`;
}
