export function generateSessionStartHook(): string {
  return `#!/usr/bin/env node
// kai-session-start — inject profile context into new Claude Code sessions
// Generated by Kai skills install. Do not edit manually.
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");

function getProfileSummary() {
  const dbPath = process.env.KAI_DB || path.join(os.homedir(), ".kai", "kai.db");
  if (!fs.existsSync(dbPath)) return null;

  try {
    const { Database } = require("bun:sqlite");
    const db = new Database(dbPath, { readonly: true });
    const traits = db.query("SELECT dimension, value, confidence FROM traits ORDER BY dimension").all();
    const identityRow = db.query("SELECT name, role FROM identity LIMIT 1").get();
    db.close();

    if (!traits || traits.length === 0) return null;
    return { identity: identityRow, traits: traits };
  } catch {
    return null;
  }
}

try {
  const profile = getProfileSummary();
  if (profile && profile.traits.length > 0) {
    const topTraits = profile.traits
      .filter(t => t.value > 0.5)
      .slice(0, 5)
      .map(t => t.dimension + "=" + t.value.toFixed(2))
      .join(", ");
    const name = profile.identity?.name ? " (" + profile.identity.name.charAt(0).toUpperCase() + ")" : "";
    console.log("Kai profile active" + name + ". Top traits: " + topTraits);
  }
} catch {
  // Hooks must not block session startup
}
`;
}
