export function generateStopHook(): string {
  return `#!/usr/bin/env bun
// kai-stop — close session, run derivation, update session stats
// Generated by Kai autopilot. Do not edit manually.
// [D7] Uses derive-shared module for rule matching (not inline RULES)
// [D17] Derive module compiled to kai-derive.cjs during hooks install
"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");

const DB_PATH = process.env.KAI_DB || path.join(os.homedir(), ".kai", "kai.db");
const MIN_SCHEMA_VERSION = 9;

try {
  if (!fs.existsSync(DB_PATH)) process.exit(0);

  const { Database } = require("bun:sqlite");
  const db = new Database(DB_PATH);

  // [D18] Schema version gate
  try {
    const row = db.query("SELECT MAX(version) as v FROM schema_version").get();
    if (!row || row.v < MIN_SCHEMA_VERSION) { db.close(); process.exit(0); }
  } catch { db.close(); process.exit(0); }

  db.run("PRAGMA busy_timeout = 5000");

  let input = "";
  try { input = fs.readFileSync(0, "utf-8"); } catch {}
  const parsed = input ? JSON.parse(input) : {};
  const sessionId = parsed.session_id || null;

  // Write stopped_at FIRST (before derivation) for orphan protection
  if (sessionId) {
    db.query("UPDATE autopilot_sessions SET stopped_at = datetime('now') WHERE session_id = ? AND stopped_at IS NULL").run(sessionId);
  }

  // Count observations from this session
  let observationsCount = 0;
  try {
    if (sessionId) {
      const row = db.query("SELECT COUNT(*) as cnt FROM observations WHERE source = 'auto_observe' AND ts >= (SELECT started_at FROM autopilot_sessions WHERE session_id = ? LIMIT 1)").get(sessionId);
      observationsCount = row ? row.cnt : 0;
    }
  } catch { observationsCount = 0; }

  // Run derivation via compiled derive module [D7/D17]
  let traitsDerived = 0;
  let derivationStatus = "skipped";

  try {
    const deriveScriptPath = path.join(__dirname, "kai-derive.cjs");
    if (fs.existsSync(deriveScriptPath)) {
      const { deriveFromRulesCore } = require(deriveScriptPath);
      // Load corrections
      const corrections = new Set(
        db.query("SELECT dimension FROM corrections").all().map(r => r.dimension)
      );
      const derived = deriveFromRulesCore(db, corrections);
      traitsDerived = derived.length;
      derivationStatus = "completed";
    } else {
      // Fallback: derive module not installed — mark as skipped
      derivationStatus = "skipped";
    }
  } catch (err) {
    derivationStatus = "failed";
  }

  // Update session stats
  if (sessionId) {
    db.query(
      "UPDATE autopilot_sessions SET observations_count = ?, traits_derived = ?, derivation_status = ? WHERE session_id = ?"
    ).run(observationsCount, traitsDerived, derivationStatus, sessionId);
  }

  db.close();
} catch {
  // Hooks must never block Claude Code shutdown
}
`;
}
